feature:
  - changed-files:
    - any-glob-to-any-file: 'lib/features/**'

ui:
  - changed-files:
    - any-glob-to-any-file: 'lib/**/*.dart'
    - any-glob-to-any-file: 'assets/**'

core:
  - changed-files:
    - any-glob-to-any-file: 'lib/core/**'
    - any-glob-to-any-file: 'pubspec.yaml'

docs:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

test:
  - changed-files:
    - any-glob-to-any-file: 'test/**'
